language: php
dist: trusty

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.cache
    - $HOME/.composer/cache

#mysql:
#  database: drupal_travis_db
#  username: root
#  encoding: utf8

before_install:
  # Travis automatically CDs into mobomo/media_webdam
  - cd ../../
  - git clone https://github.com/mobomo/media_webdam_dev
  - cd media_webdam_dev

install:
  - make vendor
  - rm -r ./modules/contrib/media_webdam/*
  - mv $TRAVIS_BUILD_DIR/* ./modules/contrib/media_webdam/

script:
  - make test-unit

after_script:
  - if [ "${TRAVIS_PHP_VERSION}" == "7.0" ]; then make report-coverage; fi;

notifications:
  slack: mobomo:IUUkblgpWtwuJjnYcBo3a2nN
  email: false
